pub(crate) const TASKS_STATE_API: &[&str] = &[
    "active_view",
    "advance_day",
    "append_query",
    "assignment_snapshot",
    "clear_active_filters",
    "clear_count",
    "clear_query",
    "collapse_notes",
    "contains_task_named",
    "current_has_notes",
    "current_is_habit",
    "current_notes_expanded",
    "current_task_id",
    "cycle_view_next",
    "cycle_view_prev",
    "daily_triage_date",
    "daily_triage_nudge",
    "enter_search",
    "expand_notes",
    "has_active_filter",
    "is_searching",
    "leave_search",
    "max_scroll",
    "new",
    "panel_model",
    "pop_query",
    "push_count_digit",
    "query_is_empty",
    "query_text",
    "replace_rows",
    "scroll_offset",
    "select_first",
    "select_last",
    "select_next",
    "select_prev",
    "selected_identity",
    "selected_link_kind",
    "selected_links_plan",
    "selection_band_rect",
    "set_assignment_filter",
    "set_view",
    "take_count",
    "tasks_per_page",
    "toggle_notes",
    "update_body_layout",
    "validate_removal",
    "visible_count",
];

pub(crate) const TASKS_STATE_TYPES: &[&str] = &[
    "DailyTriageNudge",
    "TaskAssignmentSnapshot",
    "TaskLinksPlan",
    "TasksPanelModel",
    "TasksState",
    "TasksStateInit",
];

pub(crate) const TASK_FIELDS: &[&str] = &[
    "tag_styles",
    "today",
    "full_notes",
    "expanded_notes",
    "task_options",
    "all_tasks",
    "all_habits",
    "active_view",
    "base_tasks",
    "header",
    "query",
    "in_search",
    "matcher",
    "assignment",
    "assignment_filter",
    "visible_tasks",
    "task_line_ranges",
    "selected_task",
    "pending_count",
    "body_lines",
    "visual_row_offsets",
    "scroll",
    "last_inner_height",
    "last_content_rows",
];

pub(crate) const SHELL_FIELDS: &[&str] = &[
    "main_view",
    "focus",
    "panel_side",
    "brain_rect",
    "search",
    "logs_view",
    "active_brain_tab",
];

pub(crate) const APP_COMPOSITION_FIELDS: &[(&str, &str)] = &[
    ("context", "AppContext"),
    ("tasks", "TasksState"),
    ("brain", "BrainPanelState"),
    ("shell", "ShellState"),
    ("overlay", "Option<Overlay>"),
    ("services", "AppServices"),
    ("status", "StatusState"),
    ("receiver", "crate::tui::receiver::ReceiverRuntime"),
];

pub(crate) const CONTEXT_FIELDS: &[&str] = &[
    "command",
    "config",
    "agent_kind",
    "agent_command",
    "csv_path",
    "brain_root",
    "db_path",
    "log_path",
    "server_ingress",
    "server_local_capability",
];

pub(crate) const BRAIN_FIELDS: &[&str] = &[
    "main",
    "brain_turn_active",
    "ephemeral_tabs",
    "configured_skill_sessions",
    "instance",
    "interactive_actor",
    "interactive_response_id",
    "interactive_agent_session_id",
    "resume_refusals",
    "session_actor",
    "brain_transport_override",
    "session_done_url_override",
    "session_transport_override",
    "receiver_transport_override",
];

pub(crate) const SERVICE_FIELDS: &[&str] = &[
    "agenda_runner",
    "open_runner",
    "db",
    "receiver_intent_refresher",
    "receiver_sync_runtime",
    "receiver_attachment_coordinator",
    "receiver_notice_delivery",
    "receiver_recovery_commit_visible_error",
];

pub(crate) const STATUS_FIELDS: &[&str] = &[
    "triage_day",
    "triage_gate",
    "skip_daily_triage_check",
    "flash",
    "persistent_warning",
    "alert",
    "sync_status",
    "sync_status_next_poll",
    "last_seen_downstream_id",
];
