include!("tests_support.rs");
include!("tests_parts/part_01.rs");
include!("tests_parts/part_02.rs");
include!("tests_parts/part_03.rs");
include!("tests_parts/part_04.rs");
include!("tests_parts/part_05.rs");
include!("tests_parts/part_06.rs");
include!("tests_parts/part_07.rs");
include!("tests_parts/part_08.rs");
