#!/usr/bin/env python3
"""Bake caller-supplied appendix markdown into the day's agenda markdown.

Callers may supply two markdown sources: action items (including GFM `- [ ]`
checkboxes) and a longer digest. Both source paths are explicit inputs; this
script never infers a home-directory workspace. The content is appended as
MARKDOWN to the day's agenda markdown `/tmp/<date>.md`, so it becomes the tail
of the same agenda PDF.

Why markdown, not a stapled PDF: the agenda PDF may be regenerated by several
callers. Content that lives in `/tmp/<date>.md` is rendered consistently on
every regeneration, including checkboxes and full digest text, with no
dependency on a separate PDF or pdfunite.

Two operations, both idempotent:

- **assemble** (when --actions/--newsletters are given): build the appendix
  markdown from the two sources and stage it at `/tmp/agenda-appendix-<date>.md`.
  Source headings are demoted (so the appendix's only "## " section headings are
  the two this script adds) and a leading H1 title in each source is dropped.
- **inject** (always, if a staged appendix + agenda both exist): replace any
  existing appendix in `/tmp/<date>.md` (everything from the first "## 📧 …"
  heading to EOF) with the staged appendix. Re-running never duplicates it.

This script only edits markdown. Rebuilding the agenda PDF is the caller's job.
The appendix pages are an attachment and do NOT count toward the agenda's
2-page cap, so callers do the page-count check / font-shrink on the agenda BODY
before injecting.

Paths use literal `/tmp` (NOT tempfile.gettempdir(), which is a per-user
`/var/folders/...` dir on macOS when TMPDIR is set) to match where the agenda
markdown actually lives.

Usage:
    bake_triage_appendix.py --date YYYY-MM-DD \
        [--actions <actions.md>] [--newsletters <newsletters.md>]
"""
import argparse
import re
import sys
from pathlib import Path

from _csvlib import today_iso

TMP = Path("/tmp")

# The two (and only two) "## " section headings the appendix introduces. The
# emojis keep them distinct from every agenda-body section (❗ 🔁 ✅ / plain),
# so the mutation script leaves them untouched and `strip_existing_appendix`
# can find the boundary unambiguously.
EMAIL_HEADING = "## 📧 Email triage"
NEWSLETTER_HEADING = "## 📰 Newsletter triage"
APPENDIX_MARKER = "## 📧"  # start-of-appendix sentinel (prefix match)

_ATX_RE = re.compile(r"^(#{1,6})(\s.*)$")


def agenda_md(date_iso: str) -> Path:
    return TMP / f"{date_iso}.md"


def appendix_md(date_iso: str) -> Path:
    return TMP / f"agenda-appendix-{date_iso}.md"


def _strip_leading_h1(text: str) -> str:
    """Drop a leading `# Title` line (the source's own document title) so it
    doesn't double up under the appendix's `## …` heading. Only the first
    non-blank line, and only if it's an H1."""
    lines = text.splitlines()
    for i, ln in enumerate(lines):
        if ln.strip() == "":
            continue
        if re.match(r"^#\s", ln):
            del lines[i]
            # also swallow one immediately-following blank line
            if i < len(lines) and lines[i].strip() == "":
                del lines[i]
        break
    return "\n".join(lines)


def _demote_headings(text: str) -> str:
    """Demote every ATX heading so the deepest it can sit is `###`. A source
    `##` or `#` becomes `###`; `###` becomes `####`; etc. (capped at 6). This
    guarantees the appendix body contains no `## ` line, so the only
    section-level headings in it are the two this script adds."""
    out = []
    for ln in text.splitlines():
        m = _ATX_RE.match(ln)
        if m:
            level = min(6, max(3, len(m.group(1)) + 1))
            ln = "#" * level + m.group(2)
        out.append(ln)
    return "\n".join(out)


def _prep(path_str: str | None) -> str | None:
    if not path_str:
        return None
    p = Path(path_str).expanduser()
    if not p.is_file():
        return None
    return _demote_headings(_strip_leading_h1(p.read_text())).strip()


def assemble(actions_path: str | None, newsletters_path: str | None) -> str:
    """Build the appendix markdown from the two sources."""
    actions = _prep(actions_path)
    newsletters = _prep(newsletters_path)

    parts = [EMAIL_HEADING, ""]
    parts.append(actions if actions else "_No non-newsletter action items this run._")
    parts += ["", NEWSLETTER_HEADING, ""]
    parts.append(newsletters if newsletters else "_No newsletters this run._")
    return "\n".join(parts).strip() + "\n"


def strip_existing_appendix(agenda_text: str) -> str:
    """Return the agenda text with any prior appendix removed (everything from
    the first `## 📧 …` heading onward)."""
    lines = agenda_text.splitlines()
    for i, ln in enumerate(lines):
        if ln.startswith(APPENDIX_MARKER):
            return "\n".join(lines[:i]).rstrip()
    return agenda_text.rstrip()


def inject(date_iso: str) -> bool:
    """Replace the appendix in `/tmp/<date>.md` with the staged one. Returns
    True if the agenda markdown was written, False if either file is missing."""
    staged = appendix_md(date_iso)
    agenda = agenda_md(date_iso)
    if not staged.is_file() or not agenda.is_file():
        return False
    body = strip_existing_appendix(agenda.read_text())
    combined = body + "\n\n" + staged.read_text().strip() + "\n"
    agenda.write_text(combined)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Bake caller-supplied appendix markdown into the agenda markdown."
    )
    parser.add_argument("--date", default=today_iso(), help="Agenda date (YYYY-MM-DD); defaults to today.")
    parser.add_argument("--actions", help="Path to the action-items markdown.")
    parser.add_argument("--newsletters", help="Path to the digest markdown.")
    args = parser.parse_args()
    date_iso = args.date.strip()

    if args.actions or args.newsletters:
        text = assemble(args.actions, args.newsletters)
        staged = appendix_md(date_iso)
        staged.write_text(text)
        print(f"[bake_triage_appendix] staged appendix -> {staged}")

    if inject(date_iso):
        print(f"[bake_triage_appendix] injected appendix into {agenda_md(date_iso)}")
    else:
        print("[bake_triage_appendix] nothing injected (no staged appendix and/or no agenda for date)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
